main:
  params: [args]
  steps:
  - init:
      assign:
        - project_id: $${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}

  - test_cloud_apigateway_get:
      call: http.get
      args:
        url: https://${apigw_hostname}/hello
        timeout: 5
        query:
          nickname: profile
      result: resp

  - logging_cloud_apigateway_get:
      call: sys.log
      args:
        text: $${resp}
        severity: INFO

  - test_cloud_apigateway_post:
      call: http.post
      args:
        url: https://${apigw_hostname}/hello
        timeout: 5
        body:
          nickname: profile
      result: resp

  - logging_cloud_apigateway_post:
      call: sys.log
      args:
        text: $${resp}
        severity: INFO

  - finish:
      return: "OK"
