main:
  params: [args]
  steps:
  - init:
      assign:
        - project_number: $${sys.get_env("GOOGLE_CLOUD_PROJECT_NUMBER")}

  - test_cloudrun_jobs:
      call: googleapis.run.v1.namespaces.jobs.run
      args:
        name: $${"namespaces/" + project_number + "/jobs/integration-cloud-run-jobs"}
        location: europe-west9
      result: resp

  - test_output:
      call: sys.log
      args:
        text: $${resp}
        severity: INFO

  - finish:
      return: "OK"
